---
all:
  hosts:
    node1:
      ansible_host: "{{ kubespray_single_master }}"
      etcd_member_name: etcd1
  children:
    k8s-cluster:
      children:
        kube-master:
          hosts:
            node1:
        etcd:
          hosts:
            node1:
        kube-node:
          hosts:
            node1:
