---
all:
  hosts:
    master:
      ansible_host: "{{ kubespray_master }}"
      etcd_member_name: etcd1
    worker:
      ansible_host: "{{ kubespray_worker }}"
  children:
    k8s-cluster:
      children:
        kube-master:
          hosts:
            master:
        etcd:
          hosts:
            master:
        kube-node:
          hosts:
            master:
            worker:
