galaxy_info:
  author: Ivan Kosolapov
  description: Role to generate inventory for single node kubespray deployment

  license: MIT

  min_ansible_version: 2.6

  platforms:
    - name: RHEL
      versions:
        - 7

  galaxy_tags: []

dependencies: []
