---
- name: Install git
  become: true
  yum:
    name: git
    state: present

- name: Install netaddr
  become: true
  pip:
    name: netaddr
    state: present

- name: Update kubespray
  git:
    repo: 'https://github.com/kubernetes-sigs/kubespray.git'
    dest: /home/ansible_user/kubespray

- name: Ensure inventory directory structure exists
  file:
    path: '/home/ansible_user/kubespray/inventory/stage/{{ item.path }}'
    state: directory
  with_filetree: '../templates/stage'
  when: item.state == 'directory'

- name: Ensure inventory files are populated from templates
  template:
    src: '{{ item.src }}'
    dest: '/home/ansible_user/kubespray/inventory/stage/{{ item.path }}'
  with_filetree: '../templates/stage'
  when: item.state == 'file'
