---
- hosts: cluster

  handlers:
    - name: yum clean metadata
      command: yum clean metadata
      args:
        warn: no

  tasks:
    - name: Disable stock repos
      become: true
      yum_repository:
        name: "{{ item.name }}"
        file: "{{ item.file }}"
        state: absent
      loop:
        - file: epel
          name: epel
        - file: google-cloud
          name: google-cloud-compute
        - file: google-cloud
          name: google-cloud-sdk
        - file: rh-cloud
          name: rhui-rhel-7-server-rhui-extras-rpms
        - file: rh-cloud
          name: rhui-rhel-7-server-rhui-optional-rpms
        - file: rh-cloud
          name: rhui-rhel-7-server-rhui-rh-common-rpms
        - file: rh-cloud
          name: rhui-rhel-7-server-rhui-rpms
        - file: rh-cloud
          name: rhui-rhel-7-server-rhui-supplementary-rpms
        - file: rh-cloud
          name: rhui-rhel-ha-for-rhel-7-server-rhui-rpms
        - file: rh-cloud
          name: rhui-rhel-rs-for-rhel-7-server-rhui-rpms
        - file: rh-cloud
          name: rhui-rhel-server-rhui-rhscl-7-rpms
      notify: yum clean metadata

    - name: Enable private mirrors
      become: true
      yum_repository:
        name: "{{ item }}"
        description: "{{ item }}"
        baseurl: http://{{ yum_repo_ip }}/{{ item }}
        gpgcheck: false
        enabled: true
      loop: "{{ yum_repos }}"
