---
all:
  hosts:
    ansible-controller:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
  children:
    kubernetes:
      hosts:
        master:
          ansible_host: kubernetes-master.europe-west4-a.c.openshift-playground-222412.internal
