---
- name: Disable SELinux
  become: true
  selinux:
    state: disabled

- name: Enable mirrored repos
  become: true
  yum_repository:
    name: '{{ item.name }}'
    description: '{{ item.name }}'
    baseurl: '{{ item.baseurl }}'
    gpgkey: '{{ item.gpgkey }}'
  loop: '{{ yum_mirror_repos_list }}'

- name: Install yum utils and createrepo
  become: true
  yum:
    name:
      - yum-utils
      - createrepo

- name: Sync packages
  become: true
  command: reposync -lnm --repoid={{ item.name }} --download_path={{ yum_mirror_save_dir }}
  loop: "{{ yum_mirror_repos_list }}"

- name: Create repos for packages
  become: true
  command: >-
    createrepo --update --workers={{ ansible_processor_vcpus }}
    -o {{ yum_mirror_save_dir }}/{{ item.name }}
    {{ yum_mirror_save_dir }}/{{ item.name }}
  loop: '{{ yum_mirror_repos_list }}'

- name: Download keys
  become: true
  get_url:
    url: '{{ item.gpgkey }}'
    dest: '{{ yum_mirror_save_dir }}/{{ item.name }}/gpg'
  loop: '{{ yum_mirror_repos_list }}'

- name: Set permissions for packages
  become: true
  file:
    recurse: true
    path: '{{ yum_mirror_save_dir }}'
    mode: o+r

- name: Install nginx
  include_role:
    name: jdauphant.nginx
  vars:
    ansible_become: true
    nginx_sites:
      repos:
        - listen 80 default_server
        - server_name _
        - root '{{ yum_mirror_save_dir }}'
