---
all:
  hosts:
    node1:
      ansible_host: "{{ hostvars['kube-master'].ansible_host }}"
      etcd_member_name: etcd1
  children:
    k8s-cluster:
      children:
        kube-master:
          hosts:
            node1:
        etcd:
          hosts:
            node1:
        kube-node:
          hosts:
            node1:
